version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    # staticfiles directory shared between web and nginx services
    volumes:
      - static_volume:/home/app/web/staticfiles
    # Use 'expose' rather than 'ports' so port is only exposed to other
    # docker services
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - pg
  pg:
    container_name: pg_container
    image: postgres:15
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6.15
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    env_file:
      - ./.env.prod.db
    ports:
      - 5433:5433
    depends_on:
      - pg
  nginx:
    build: ./nginx
    # staticfiles directory shared between web and nginx services
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  pg_data:
  pgadmin_data:
  static_volume:
