version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - pg
  pg:
    container_name: pg_container
    image: postgres:15
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6.15
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    env_file:
      - ./.env.prod.db
    ports:
      - 5433:5433
    depends_on:
      - pg

volumes:
  pg_data:
  pgadmin_data:
